on: 
  push:
    branches:
      - master

name: Master branch CI

jobs:
  build-jekyll:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site in the jekyll/builder container
        run: docker build .
  check-assets:
    name: Format and test CSS and JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
